"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRoutes = void 0;
const express_1 = require("express");
const client_1 = require("@prisma/client");
const auth_controller_1 = require("./auth.controller");
const auth_service_1 = require("./auth.service");
const router = (0, express_1.Router)();
exports.authRoutes = router;
const prisma = new client_1.PrismaClient();
const authService = new auth_service_1.AuthService(prisma);
const authController = new auth_controller_1.AuthController(authService);
router.post('/register', authController.register);
router.post('/login', authController.login);
